### ISSUE TITLE
OSError: SavedModel file does not exist at: ./model/model_cpp/cpp_predictor.hdf5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by sailfish009** [learningmatter-mit/peptimizer#1]
Hi, i am trying to run CPP in linux console.
gettting following error message:

https://github.com/sailfish009/peptimizer/blob/master/INSTALL.md

https://github.com/sailfish009/peptimizer/blob/master/CPP.py

```
$ py --version
Python 3.7.9

$ py CPP.py 
Loading Data for Training of Generator
Pre-Processing Data for Generator
Featurizing Data for Generator
Starting Training of Generator
2020-10-19 09:03:58.436171: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-10-19 09:03:58.460029: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3493330000 Hz
2020-10-19 09:03:58.461109: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5624daedbfd0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-19 09:03:58.461133: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-19 09:03:58.461215: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:From /opt/conda/envs/CPP/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:1666: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 5987 samples, validate on 2567 samples
2020-10-19 09:03:58.859768: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Epoch 1/2
5987/5987 [==============================] - 2s 311us/sample - loss: 2.9281 - accuracy: 0.1593 - val_loss: 2.7133 - val_accuracy: 0.1944
Epoch 2/2
5987/5987 [==============================] - 1s 228us/sample - loss: 2.6928 - accuracy: 0.1882 - val_loss: 2.6680 - val_accuracy: 0.1944
Loading Data for Training of Predictor
Featurizing Data for Predictor
Creating Model for Predictor
Train on 409 samples, validate on 103 samples
Epoch 1/2
409/409 [==============================] - 4s 10ms/sample - loss: 1.0964 - val_loss: 0.5530
Epoch 2/2
409/409 [==============================] - 4s 10ms/sample - loss: 0.4856 - val_loss: 0.4778
Traceback (most recent call last):
  File "CPP.py", line 55, in <module>
    seq_max = SEQ_MAX
  File "/work/working/peptimizer/utils/utils_cpp/cpp_optimizer.py", line 93, in __init__
    seq_max = self.__seq_max
  File "/work/working/peptimizer/utils/utils_cpp/cpp_predictor.py", line 107, in __init__
    self.model = load_model(self.__model_path)
  File "/opt/conda/envs/CPP/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 189, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/opt/conda/envs/CPP/lib/python3.7/site-packages/tensorflow/python/saved_model/loader_impl.py", line 113, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: ./model/model_cpp/cpp_predictor.hdf5/{saved_model.pbtxt|saved_model.pb}
```

**Comment by pikulsomesh** [comment]
The pre-trained predictor can be downloaded from the link in https://github.com/learningmatter-mit/peptimizer/blob/master/model/model_cpp/README.md
